set_languages("c++20")
add_rules("mode.debug", "mode.release")

includes("rlib")
includes("vk")
includes("mesh")
includes("mesh_simplify")
includes("virtual_mesh")
includes("util")
includes("vk_win")
includes("program")
