add_requires("vulkansdk","glfw")

target("vk")
    set_kind("shared")
    add_rules("utils.symbols.export_all", {export_classes = true})
    add_files("**.cpp")
    add_deps("rlib",{public=true})
    add_deps("vk-bootstrap")
    add_packages("vulkansdk","glfw")
target_end()