add_requires("vulkansdk")

target("vk")
    set_kind("static")
    -- add_rules("utils.symbols.export_all", {export_classes = true})
    add_files("**.cpp")
    add_includedirs(".",{public=true})
    add_deps("rlib",{public=true})
    add_deps("util",{public=true})
    add_packages("vulkansdk")
target_end()